[[ZipFlow]]
arch = "aarch64"
git-tree-sha1 = "c7e2718b6bad4e83185046a3d6f3399a0a84f8ea"
os = "macos"

    [[ZipFlow.download]]
    sha256 = "63c6e3a26c45f5932726ad19b0c986bc7a239b2af6cb787690b39044d55cee96"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.aarch64-apple-darwin.tar.gz"
[[ZipFlow]]
arch = "aarch64"
git-tree-sha1 = "727d052a3fa7dc18c013f943f4cd70a11d129b4e"
libc = "glibc"
os = "linux"

    [[ZipFlow.download]]
    sha256 = "5d03a3b9be31b3bc5e4a0c81d4fb631d557f3d1e91d2962eb576c27e1219a2ea"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.aarch64-linux-gnu.tar.gz"
[[ZipFlow]]
arch = "aarch64"
git-tree-sha1 = "c86adb8aebd437aa2c14ba73c51eab149a15f2cb"
libc = "musl"
os = "linux"

    [[ZipFlow.download]]
    sha256 = "9ddc1cb2a2f028c0cfc6ff305cfb048a21fc6875c3c2b2589cb8be06d4fdaa85"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.aarch64-linux-musl.tar.gz"
[[ZipFlow]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3a248052889337c7d22d177b1ba512725229d321"
libc = "glibc"
os = "linux"

    [[ZipFlow.download]]
    sha256 = "f1b8b6859362c8332198b40f1a37f0a3b16e9a9eb3ff38186e24dbb229b36b4a"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.armv6l-linux-gnueabihf.tar.gz"
[[ZipFlow]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "213573646c5e4f47c78e6e476fa2461ed4d97aa8"
libc = "musl"
os = "linux"

    [[ZipFlow.download]]
    sha256 = "3c620d3ba731effefafe5e768190aac3e91449b790803fd118f69114232c170c"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.armv6l-linux-musleabihf.tar.gz"
[[ZipFlow]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "596e969fd2883b360364b64409266f4607163445"
libc = "glibc"
os = "linux"

    [[ZipFlow.download]]
    sha256 = "7c7ae515dce9e8903e842f5cf3809a62626c1f3923325511e3027b5ad2222067"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.armv7l-linux-gnueabihf.tar.gz"
[[ZipFlow]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94e2b55d9ce3795e03d5d90929016eecb27c954e"
libc = "musl"
os = "linux"

    [[ZipFlow.download]]
    sha256 = "496820a263d625ffd2b8b34903bf3b8af0da5c9756a4cc35ec1a4d3e139c0067"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.armv7l-linux-musleabihf.tar.gz"
[[ZipFlow]]
arch = "i686"
git-tree-sha1 = "c2661d1d9cfc486347f3fcd80975a1b68dee6ac1"
libc = "glibc"
os = "linux"

    [[ZipFlow.download]]
    sha256 = "b4e28cc799909431c79801ebeb95bdbdc6730da4b4d12beae3bc7c3696025e57"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.i686-linux-gnu.tar.gz"
[[ZipFlow]]
arch = "i686"
git-tree-sha1 = "b9f09b99493a59cbfb8376311bddfabcadbefdaf"
libc = "musl"
os = "linux"

    [[ZipFlow.download]]
    sha256 = "0b08076eeb43451340953902324f66ead2d48f60d1641344831d87444b9add43"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.i686-linux-musl.tar.gz"
[[ZipFlow]]
arch = "i686"
git-tree-sha1 = "4d0d34f135e5cf1eac19f7071606da8ec64ff2cd"
os = "windows"

    [[ZipFlow.download]]
    sha256 = "4c01aee7c423671c113b6c735731d463ddd2822bb914a4c82ff5973f8ac2614b"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.i686-w64-mingw32.tar.gz"
[[ZipFlow]]
arch = "powerpc64le"
git-tree-sha1 = "f72bc97bd9aa63bacc8ede3b194f7efb85923c5d"
libc = "glibc"
os = "linux"

    [[ZipFlow.download]]
    sha256 = "fc66aae612b507ef5f2afb0ac33e80f931a9a734a47e424f6df68b7e9cd882e1"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.powerpc64le-linux-gnu.tar.gz"
[[ZipFlow]]
arch = "x86_64"
git-tree-sha1 = "7ef75713e2616481275ecfa881b4ee78a2b71b89"
os = "macos"

    [[ZipFlow.download]]
    sha256 = "58eeb882f104b59a53f073ca558c5e87d3a0caf54e1af5fe482c7300ef5dad4c"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.x86_64-apple-darwin.tar.gz"
[[ZipFlow]]
arch = "x86_64"
git-tree-sha1 = "a032ecc11358952cdfdc566f0ad0ed87d5cdbe3a"
libc = "glibc"
os = "linux"

    [[ZipFlow.download]]
    sha256 = "2643dd68bde888283353e76606fad04439aeb766fb63dfd7462a2285e3f448fb"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.x86_64-linux-gnu.tar.gz"
[[ZipFlow]]
arch = "x86_64"
git-tree-sha1 = "ebb18729fbbee5734c0f584a8c4e870bfade1dd1"
libc = "musl"
os = "linux"

    [[ZipFlow.download]]
    sha256 = "f32fe6e060d02617e45c91c199ed536af39f1a7de09d2c6f3b9dc76e7e5293b7"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.x86_64-linux-musl.tar.gz"
[[ZipFlow]]
arch = "x86_64"
git-tree-sha1 = "13c183273ccf3dd71c07b9f22d60e266724b4d98"
os = "freebsd"

    [[ZipFlow.download]]
    sha256 = "eed64c74a23a05adca6fd349e11bc8845a9bdd6d680e4a6a9855bd407ac219f5"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.x86_64-unknown-freebsd.tar.gz"
[[ZipFlow]]
arch = "x86_64"
git-tree-sha1 = "f0334d8fad0715769d866a198df4216b466480a0"
os = "windows"

    [[ZipFlow.download]]
    sha256 = "59bb595d56544682dadcae904cecebaf1219e3a5ca26d48f2d49aae73fec8819"
    url = "https://github.com/JuliaBinaryWrappers/ZipFlow_jll.jl/releases/download/ZipFlow-v1.1.0+0/ZipFlow.v1.1.0.x86_64-w64-mingw32.tar.gz"
